---
- hosts: all
  become: yes

  tasks:
  - name: Ensure docker (for time synchronization) is installed.
    yum:
      name: docker
      state: present

  - name: Ensure docker is running.
    service:
      name: docker
      state: started
      enabled: yes

# The same as the above play, but in super-compact form!
- hosts: all
  become: yes
  tasks:
  - yum: name=docker state=present
  - service: name=docker state=started enabled=yes

- hosts: all
  become: yes
  tasks: 
  - name: Pull an image
    community.docker.docker_image:
      name: flesh222/demoforhsbc:v3
      source: pull
      # Select platform for pulling. If not specified, will pull whatever docker prefers.

  - name: Create a data container
    community.docker.docker_container:
      name: mydemo
      image: flesh222/demoforhsbc:v3
      ports:
      # Publish container port 9000 as host port 8080
        - "80:8001"