---
- hosts: all
  become: yes

  tasks:
  - name: Ensure docker (for time synchronization) is installed.
    yum:
      name: docker
      state: present

  - name: Ensure docker is running.
    service:
      name: docker
      state: started
      enabled: yes

# The same as the above play, but in super-compact form!
- hosts: all
  become: yes
  tasks:
  - yum: name=docker state=present
  - service: name=docker state=started enabled=yes